services:

  backend_1:
    image: scaling-study-backend:latest
    environment:
      INSTANCE_ID: 'RPLCA-A'
    volumes:
      - ./storage/backend/rplca-a/:/home/node/app/storage/app

  backend_2:
    image: scaling-study-backend:latest
    environment:
      INSTANCE_ID: 'RPLCA-B'
    volumes:
      - ./storage/backend/rplca-b/:/home/node/app/storage/app

  backend_3:
    image: scaling-study-backend:latest
    environment:
      INSTANCE_ID: 'RPLCA-C'
    volumes:
      - ./storage/backend/rplca-c/:/home/node/app/storage/app

  nginx:
    image: nginx:alpine
    volumes:
      - ./storage/logs/:/var/log/nginx
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8080:80
